---
- hosts: all
  become: true
  vars:
    mobsf_opt_path: '/opt/MobSF'
  tasks:
    - name: MobSF install prep
      block:

        - name: installing deps
          apt:
            state: present
            name:
              - git
              - python3
              - openjdk-8-jdk
              - python3-venv
              - python3-pip
              - python3-dev
              - build-essential
              - libffi-dev
              - libssl-dev
              - libxml2-dev
              - libxslt1-dev
              - libjpeg8-dev
              - zlib1g-dev
              - wkhtmltopdf

    - name: MobSF install
      block:

        - name: pip installing github3 for GH release module
          pip:
            name: github3.py

        - name: MobSF latest release
          github_release:
            user: MobSF
            repo: Mobile-Security-Framework-MobSF
            action: latest_release
          register: release_version

        - name: Cloneing latest MobSF repo
          git:
            repo: https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
            dest: "{{ mobsf_opt_path }}"
            version: "{{ release_version.tag }}"

        - name: installing pipenv env deps
          import_role:
            name: elreydetoda.pipenv.pipenv_init
          vars:
            pip_path: '/usr/local/bin/pip3'

        - name: installing pipenv pyenv
          import_role:
            name: elreydetoda.pipenv.pyenv

        - name: getting most recent python3.9 version
          shell: "{{ ansible_user_dir }}/.pyenv/bin/pyenv install --list | grep -oP '3\\.9\\.\\d+' | sort -Vr | head -n1"
          register: python_version
          changed_when: False

        - name: installing python version
          command:
            cmd: '{{ ansible_user_dir }}/.pyenv/bin/pyenv install {{ python_version.stdout }}'
            creates: '{{ ansible_user_dir }}/.pyenv/versions/{{ python_version.stdout }}'

        - name: adding Pipfile to repo
          ansible.builtin.copy:
            dest: '{{ mobsf_opt_path }}/Pipfile'
            content: |
              [[source]]
              url = "https://pypi.org/simple"
              verify_ssl = true
              name = "pypi"

              [packages]

              [dev-packages]

              [requires]
              python_version = "3.9"


        - name: Running install script
          command: pipenv run ./setup.sh
          args:
            chdir: "{{ mobsf_opt_path }}"
            creates: "{{ mobsf_opt_path }}/venv/bin/activate"

    - name: setting MobSF aliases
      vars:
        vagrant_aliases: ~vagrant/.bash_aliases
      block:

        - name: ensure file exists
          copy:
            content: ""
            dest: "{{ vagrant_aliases }}"
            force: no
            group: vagrant
            owner: vagrant
            mode: 0644

        - name: setting MobSF start alias
          lineinfile:
            path: "{{ vagrant_aliases }}"
            regexp: '^alias si-mobsf_start='
            line: 'alias si-mobsf_start="sudo -i bash -c \"pushd /opt/MobSF/ && pipenv run ./run.sh\""'
